cattle-ops/terraform-aws-gitlab-runner

CHNAGELOG.md, template/logging.tpl, template/user-data.tpl
=> Fix non starting runner instance

CHANGELOG.md, README.md, examples/runner-public/main.tf, main.tf, outputs.tf, template/runner-config.tpl, variables.tf
- Missing documentation makes setup fail #31
- Shared cache is not working #33
=> Bugfix for #31 and #33

README.md
=> Small typos fix

README.md, examples/runner-default/README.md, examples/runner-default/variables.tf, examples/runner-docker/README.md, examples/runner-docker/variables.tf, examples/runner-pre-registered/README.md, examples/runner-pre-registered/variables.tf, examples/runner-public/README.md, examples/runner-public/variables.tf, main.tf, template/logging.tpl, template/runner-config.tpl, variables.tf
Just a few spelling corrections and some opinionated updates to the README/variable descriptions.
=> Spelling and grammer updates

main.tf
See #61 
NO
Used public example for verificatens.
No changes
=> :bug: Fix #61 - terraform alwasy indicate a changeset

template/gitlab-runner.tpl
This is about detecting failure and retrying the docker machine download from Github.
NO.
I haven't verified the examples (it's a bit hard to test this case, since it needs Github to be failing with something other than 404), but I made sure to test manually the curl command against a local endpoint returning 500, i works like this:
```
$ time curl --fail --retry 6 -L http://127.0.0.1:5000/ >/dev/null && echo oi || echo failed
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Warning: Transient problem: HTTP error Will retry in 1 seconds. 6 retries 
Warning: left.
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0 …
```
=> Detect and retry when docker machine download fails (fixes #72)

main.tf
update naming for security group rules for the docker machine sg
No
default sample.
=> Update names for docker machine security-rules

README.md, _docs/TF_MODULE.md, variables.tf
Upgrade default runner version to 12.1.0
NO
runner-default
Updates
=> Update default runner version to 12.1.0

CHANGELOG.md, README.md, _docs/TF_MODULE.md, main.tf, tags.tf, template/user-data.tpl, variables.tf
Disable xtrace log in user daa
NO
runner-default
updated
=> Fix #49 - disable xtrace logging by default

README.md, _docs/README.md, ci/bin/autodocs.sh
Create script to generate links for terraform registry, see #63 
NO
docs generation
done
=> Fix #63 broken example links

ci/bin/run-local.sh, ci/bin/terraform.sh, ci/bin/verify-examples.sh, ci/bin/verify.sh
Fix CI script. Examples are now checked as well.
NO
build
n/a
=> Fix ci script

cache/main.tf
As part of security improvements, the s3 encryption is the best practices
No required.
No apply
No apply
=> Enable s3 encryption

CHANGELOG.md, README.md, _docs/TF_MODULE.md, variables.tf
Update docker machine to 0.16.2 by default
NO
updated
=> Set docker machine version by default to 0.16.2

template/gitlab-runner.tpl
Fixing Docker Machine Certification Generation (fixing #143 )
NO
Verified using public example
N/A
=> Fixing Docker Machine Cerficiation Generation

template/gitlab-runner.tpl
=> Fixing Docker Machine Cerficiation Generation #143

main.tf, variables.tf
Encrypt runner root device by default #162
NO
=> Encrypt runner root device

main.tf, variables.tf
- Update version to 12.8.0
- Remove terraform deprecate constucts
NO
runner-default example
=> Improvements

README.md, cache/README.md, cache/_docs/TF_MODULE.md, cache/main.tf, cache/variables.tf
Add variables to improve the configuration of the cache
NO
default sample
=> dd variables for cache

main.tf
Fix for missing policy in case cache is not managed #206 
NO
example pubic and default
=> #206 - Fix missing policy for existing cache

main.tf, variables.tf
Add a new variable to add a list of policies to be added to the runner's role.
Closes #155 
No
No verification done. I have no cloud account at hand.
Documentation updated.
=> Add IAM policies for runner as variable

README.md, variables.tf
Upgrade gitlab default runner version
=> upgrade default version for gitlab runner to 13.4.0

.pre-commit-config.yaml, README.md, examples/runner-default/main.tf, examples/runner-default/providers.tf, examples/runner-default/versions.tf, examples/runner-docker/main.tf, examples/runner-docker/providers.tf, examples/runner-docker/versions.tf, examples/runner-pre-registered/main.tf, examples/runner-pre-registered/providers.tf, examples/runner-pre-registered/versions.tf, examples/runner-public/main.tf, examples/runner-public/providers.tf, examples/runner-public/versions.tf, main.tf, variables.tf
Upgrade versions in examples
NO
Default example
=> fix: Upgrade vpc module and provider versions

bin/cancel-spot-instances.sh, examples/runner-default/main.tf, examples/runner-public/main.tf
Revert cancel spot instances removed due to CI refactoring
NO
=> fix(examples): revert cancel spot instance script

README.md, variables.tf
resolves #308 #299
NO
Default example
=> fix: updated docker machine default url

README.md
Update README Usage module example
=> Add right double quote to README my-token

CHANGELOG.md, main.tf
=> use ebs gp3

README.md, main.tf, variables.tf
upgrade default runner version to 14.0.1
NO
=> feat: upgrade default runner version to 14.0.1

CHANGELOG.md, README.md, main.tf, variables.tf
Add ability to define throughput for root block device on runner
=> feat: Add ability to define throughput for root block device on runner

main.tf, template/runner-config.tpl, variables.tf
Merging the work of #472 and #483
Added some fixes
- Inject variable in template
- Remove logic to callcurate setting as suggested in #472 and simple use a variable as suggested in #483
NO
Default example
=> chore: merge Authentication type

README.md
Added a missing quote in the README
NO - If yes please describe the migration.
N/A
=> docs: add missing quote

.github/workflows/ci.yml, modules/terminate-instances/iam.tf
Introduce a TfSec scan (see https://github.com/aquasecurity/tfsec) to make sure that potential security risks are found. TfSec is a static code analysis tool.
No
Check that the action is started for a PR.
=> ci: scan Terraform code for potential security risks

README.md
=> Minor README typo fix

README.md, main.tf, variables.tf
Closes #585 
NO
None. I've locally tested the "try" logic in `terraform console` to ensure it works with / without the overrides.
=> feat(asg): Add fine-grained options for schedule_config scale_in and scale_out

.github/workflows/release.yml
Remove harded bootstrap of release
n/a
n/a
=> chore: Clean up release migration

main.tf
* Add remarks to explain traps in the code
* Format code
* leave the comment, no code changes
A few sentences describing the overall goals of the pull request's commits.
YES | NO - If yes please describe the migration.
=> docs: detail the usage of S3 cache policy (#427)

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
I did some research for issue templates to make sure that bug and feature reports have all necessary information included. This is the first proposal.
=> chore: add issue templates for bugs and feature requests

.github/workflows/pr-opened.yml
This PR adds a new workflow which posts a comment to every opened PR welcoming the pull request and making some important information available to the author (contribution guidelines, license).
=> ci: add workflow to welcome a new PR

README.md
=> docs: update notices in README

.github/dependabot.yml
Configuration of dependabot for github action is incorrect. 
NO
n/a
=> chore: fix dependabot config for github actions

.github/workflows/lint_pr_title.yml
Fix pr-lint after moving repo.
NO
ci
=> chore: fix pr-lint

.github/workflows/release.yml
=> chore: fix reference to release app and secret after repo move

CHANGELOG.md, README.md, variables.tf
Remove occurrences of a typo
NO
N/A
=> docs: typo - consecutive 'the' occurrences

README.md
With release v7 the variables were renamed but this change was not done in README.md.
None. Docs only.
=> docs: adjust code snippets to new variable structure (v7)

.cspell.json, .github/workflows/auto-approval.yml
... this save manual work on the maintainers side. Manual approval is not really necessary here.
=> ci: approve Renovate PRs automatically

docs/usage.md, modules/terminate-agent-hook/README.md
Some code samples are still showing the old variable structure. This PR refactors all code in the documentation, adapting it to the new variable structure.
Closes #1053
=> docs: adapt to new variable layout
