CHNAGELOG.md, README.md, bucket.tf, examples/runner/terraform.tfvars, main.tf, template/gitlab-runner.tpl, variables.tf
- Add parameter for docker machine version
- Upgrade default gitlab runner version to 11.0.0
- Upgrade default docker-machine version to 0.15.0
=> Upgrade gitlab runner and docker machine

README.md, variables.tf
I updated the default config for the runner to 11.3.1, The Markdown linter kicked in and I decided to fix some typos and make the markdown a bit better readable.
=> Update Gitlab Runner to 11.3.1

README.md, bucket.tf, variables.tf
Sometimes you may want to run more than one of these instances per AWS account :)  Allowing an optional prefix enables unique bucket names to be configured, without breaking existing installations.
=> Add `cache_bucket_prefix`, to allow for unique bucket names

README.md, main.tf, template/gitlab-runner.tpl, variables.tf
This commit introduces two new variables, intended to be used to allow
scriptlets to be inserted before and after the runner install (but
before the runner is started) in the user-data configuration.
=> Add pre/post install user-data snippets for runners

README.md, main.tf, template/runner-config.tpl, variables.tf
Hi, @npalm!
This PR introduces configurable docker image for runners.
In our case we need the ability to use custom images, because we work with private docker registries and need to configure credential helpers to perform pulls from them. To handle this, I've added the variable `runners_image` with default value `docker:18.03.1-ce`. So without setting this variable everything should work as before.
=> Configurable docker image for runner

variables.tf
* Fix example in comment for `docker_machine_options` - prepending the `--` is not necessary (in fact, breaks..)
* Fix typo too
=> Fix comment for docker_machine_options (#35)

CHANGELOG.md, README.md, template/runner-config.tpl, variables.tf
* Add new variable for AWS Availability Zone, with default `a` (as implied it seems)
* Specify zone explicitly in `MachineOptions`
* Update documentation
* Update changelog
This fixes #35
=> Add AWS Zone support (#35)

main.tf, template/runner-config.tpl, variables.tf
After experiencing issues with our CI pipeline failing we realized it was related to not having shared memory for chrome, as related here: https://github.com/elgalu/docker-selenium/issues/20
I've added a variable to the recipe that defaults to 0 (to match the current value) so that this can be set in the runners config.toml.
Let me know if you have any suggestions on this PR, wasn't sure the best way to contribute to this project.
=> Added variable for shm_size in the runner config.toml.

main.tf, variables.tf
This PR addresses issue #47 and also adds a way of limiting SSH ingress to a list of CIDR blocks.
=> Add option to disable SSH to the runner instance

README.md, _docs/README.md, _docs/TF_MODULE.md, ci/bin/autodocs.sh, examples/runner-default/_docs/README.md, examples/runner-default/_docs/TF_MODULE.md, examples/runner-docker/_docs/README.md, examples/runner-docker/_docs/TF_MODULE.md, examples/runner-pre-registered/_docs/README.md, examples/runner-pre-registered/_docs/TF_MODULE.md, examples/runner-public/_docs/README.md, examples/runner-public/_docs/TF_MODULE.md
Hey @npalm 
I wrote some bash that wraps `terraform-docs` and `pandoc` to auto-generate the terraform documentation. As part of this, I've moved the 'base' READMEs to a `_docs` folder for each module. The resulting README.md should look like same with the one exception being that the `terraform-docs` table is now appended to the end of each module's README.md. 
Assuming I'm not too far from the mark I guess the next step is integrating this into the existing CI?
I held off on adding a blurb to the main README.md on how to generate these docs b/c I wasn't sure if those types of instructions would work better in a contribution guidelines doc or as a separate contributing heading in the README. There are a few boilerplate templates out there for the standalone contributing docs but I didn't …
=> Automates terraform documentation generation

main.tf
Fix for #64 removed unused security group
NO
runners-public
=> Fix #64 - remove unused security group add SSH rule to runner group

main.tf
Before this PR, setting `enable_manage_gitlab_token` to `false` made the plan fails (see #68)
NO
runner-default
=> Fix #68 - add count to prevent resource creation failing

policies/instance-docker-machine-policy.json
see #70 
NO
runner-default
no change
=> Fix #70 - update policy to allow runners to start when not using spot instances

main.tf
This fixes the issue #75 the runner is not reachable when the following conditions satisfy:
- `runners_use_private_address = false`
- the subnet is public (i.e. the default route is to an Internet Gateway)
- `map_public_ip_on_launch` of the subnet is default
No.
Tested with the example project: https://github.com/int128/aws-gitlab-runner-starter.
No change.
=> Fix runner is not reachable when runners_use_private_address = false

template/gitlab-runner.tpl
If the gitlab-runner tries to spin up multiple machines when it's first
initialized it runs docker-machine commands in parallel which can
cause it to generate competing certificates. To avoid that have
docker-machine create a dummy-machine first.
https://gitlab.com/gitlab-org/gitlab-runner/issues/3676
NO
Please ensure you pdate the README in `_docs/README.md`. The README.md in the root can be update by running the script `ci/bin/autodocs.sh`
=> Fix: docker-machine cert generation

README.md, _docs/TF_MODULE.md, bucket.tf, variables.tf
Add `cache_bucket_versioning` variable that allows you to toggle
whether bucket versioning is enabled on the cache bucket. Defaults
to false.
NO
default
Please ensure you update the README in `_docs/README.md`. The README.md in the root can be update by running the script `ci/bin/autodocs.sh`
=> Add variable for bucket versioning

README.md, variables.tf
changes the description for the variable `enable_manage_gitlab_token`, since the second part of the description is misleading
NO
tried to build the infrastructure with this module and believed the wrong part of the description. So, I had chosen the wrong value for this variable.
README was updated
=> Fix misleading variable description

ci/bin/autodocs.sh, ci/bin/verify-examples.sh
fix small issues with the ci scripts:
- autodocs.sh did not exit if pandoc or terraform-docs were not installed
- ci/bin/verify-examples.sh had incorrect check for examples and printed some useless  errors
NO
N/A
N/A
=> ci script update

README.md, _docs/README.md, _docs/TF_MODULE.md, main.tf, template/runner-config.tpl, variables.tf
Adding additional parameter to specify the Docker Pull Policy for the Gitlab Runner
NO
has been in production in our setup for a few weeks with parameter if-not-present. default value is the default from Gitlab
Documentation was updated to include the additional parameter. Also it was updated from upstream and fixed minor autodoc issue.
=> Adding docker pull policy Parameter

main.tf, template/runner-config.tpl, variables.tf
The default image used for the docker-machine EC2 instances is rather old. In this PR this is changed to use the latest AMI of Ubuntu 18.04 available on AWS EC2.
NO
Works without problems in our installation for a few weeks
=> use latest ubuntu 18.04 for gitlab runner instances

examples/runner-default/main.tf, examples/runner-docker/main.tf, examples/runner-pre-registered/main.tf, examples/runner-public/main.tf
Use valid availability zones when using a region other than `eu-west-1`.
NO - If yes please describe the mirgration.
Please mentioned the examples you have verified.
Please ensure you pdate the README in `_docs/README.md`. The README.md in the root can be update by running the script `ci/bin/autodocs.sh`
=> fix: availability zone in AWS region

examples/runner-default/README.md, examples/runner-default/_docs/TF_MODULE.md, examples/runner-default/main.tf, examples/runner-default/variables.tf, examples/runner-pre-registered/README.md, examples/runner-pre-registered/_docs/TF_MODULE.md, examples/runner-pre-registered/main.tf, examples/runner-pre-registered/variables.tf
I want to be able to specify the timezone used for idle time in a variable.
NO - If yes please describe the mirgration.
Please mentioned the examples you have verified.
=> fix: use a variable to determine timezone

.github/pull_request_template.md, README.md, examples/runner-public/main.tf, main.tf, outputs.tf, template/gitlab-runner.tpl, template/runner-config.tpl, variables.tf
This will add an optional Docker socket mount as an alternative (opinionated to be better) option to privileged mode
NO
It works with default example in our setup
Updated
=> Mount docker socket

template/runner-config.tpl
Looks like `runners_iam_instance_profile_name` was documented but never used
=> Use runners_iam_instance_profile_name

README.md, _docs/TF_MODULE.md, main.tf, variables.tf
I updated the description of the `instance_role_json` variable as the it was not accurate, the json template passed is applied on the `runners-default-instance-role` and not the `runners-default-docker-machine-role`.
I also removed the unused `instance_role_runner_json` variable as it was only define as variable and replaced it with a new `docker_machine_role_json` variable that allows customization of the policy of the `runners-default-docker-machine-role` role.
The behavior is the same than before if a user does not use the new `docker_machine_role_json` variable.
No.
Validated on a private gitlab instance but please do validate as well.
Documentation has been updated using the autodocs.sh script.
=> Add variable docker_machine_role_json allowing role policy customization

README.md, _docs/TF_MODULE.md, main.tf, variables.tf
My company uses CloudSploit (https://cloudsploit.com/) to monitor our AWS account, the current configuration causes alerts because of the ingress configuration of the docker machine instance. As such, I added the `docker_machine_ssh_cidr_blocks` to allow the configuration of this value like the `gitlab_runner_ssh_cidr_blocks` variable does.
No
Deployed on a private instance.
Documentation has been updated.
=> Add variable docker_machine_ssh_cidr_blocks allowing ssh ingress restriction

README.md, _docs/TF_MODULE.md, main.tf, template/runner-config.tpl, variables.tf
One of the needs of my team is to build docker image from Gitlab, to do that we currently use this option https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-docker-socket-binding and therefore need to be able to customize the volumes set in the `config.toml` template.
This pull request adds support for that and default to `["/cache"]` if not provided to support the existing behavior.
Usage in my case:
```
runners_volumes = ["/cache", "/var/run/docker.sock:/var/run/docker.sock"]
```
No
Deployed and validated on a private gitlab instance.
Updated.
=> Add runners_volumes variable

examples/runner-default/main.tf, tags.tf
Fix the generation of etc2 instance tags in runner userdata when the name or value of a tag contains a ":".  Fix for #111 .
NO
default-runner-example now includes these tags, ran that example and verified the userdata sent to those boxes has the tags split correctly.
Should not be required, no interface change.
=> Namespace tags

cache/main.tf, cache/variables.tf, main.tf, variables.tf
The IAM roles that we use for deployment require us to use certain resource name prefixes, along with the account ID and suffix this was pushing the cache bucket name over the 63 character limit imposed by AWS.
I have added an input variable to make the account ID in the bucket name optional as we did not require it, but wanted to maintain backwards compatibility for others.
NO
We have deployed the module to our environments.
=> Cache bucket name optional account

README.md, _docs/TF_MODULE.md, locals.tf, main.tf, template/runner-config.tpl, variables.tf
Adds the Gitlab Runner `MaxBuild` configuration option, which terminates instances that have run a certain number of builds.
NO 
Ran `runner-default` which works with both `0` `MaxBuild` (which disables the option) and `1` `MaxBuild` where the instance is destroyed after 1 build.
Updated :)
=> Add MaxBuilds variable to gitlab runner config

main.tf, variables.tf
In some cases it may be useful to not pay for an instance outside of working hours. Using ASG's scheduling actions it can be easily achieved using a CRON syntax for recurrence.
NO.
TODO
=> Enable ASG scheduling

_docs/TF_MODULE.md, main.tf, variables.tf
This fixes https://github.com/npalm/terraform-aws-gitlab-runner/issues/80 by allowing to use specific/dedicated input variables for configuring the EBS volume types and size attached to the instance.
YES - while I'm setting the default to `8`GB drift might still be created depending on the existing/running launch configuration.
`plan` and `apply`.
=> Allow for configurable root block size

variables.tf
Bump gitlab-runner to 12.2.0.
NO
Tested on personal infra.
OK
=> Bump gitlab-runner to 12.2.0

variables.tf
Bump gitlab-runner to 12.3.0. That released at Sep 09
NO
Tested on personal infra
Ok
=> Bump gitlab-runner to 12.3.0

README.md, outputs.tf
Just adding outputs for a security group IDs to simplify integration of resources created by this module with existing network setups.
NO
The default example is working, others should be working too.
Added new outputs to docs.
=> Adding outputs for agent and runner security groups

README.md, _docs/TF_MODULE.md, examples/runner-default/main.tf, main.tf, outputs.tf, template/runner-config.tpl, template/volumes.tpl, variables.tf
Closes #104 
Adds the ability to add temporary file systems to main and service containers.
A few sentences describing the overall goals of the pull request's commits.
NO. Defaults are empty and work out of the box.
- Verified, that Gitlab Runner starts with 0,1 and 2 Different temporary Volumes in main and service container
- Verified by running `ci/bin/run-local.sh`
Documentation has been updated
=> Additon Options to specify tmpfs volumes in main and service containers

README.md, _docs/TF_MODULE.md, main.tf, variables.tf
Related to https://github.com/npalm/terraform-aws-gitlab-runner/pull/101, make the ingress CIDR configurable for the docker port 2376 security group rule.
No, default value of the new variable is the original value.
=> Add variable docker_machine_docker_cidr_blocks allowing docker ingress restriction

main.tf
Alternative to https://github.com/npalm/terraform-aws-gitlab-runner/pull/139 as I dont think we need to expose the docker port to the world. Just to the gitlab runner instance and maybe the other docker machines?
NO
=> Lock down docker port access to only the runner security group

variables.tf
This was in the original version of the module and appears to be no
longer used.
NO
Just did grep -r to confirm the var isn't used anywhere.
Not mentioned in doco so nothing to update.
=> Remove docker_machine_user variable

variables.tf
This variable appears to be no longer used anywhere.
NO
Grep -r.
No docs to update.
=> Delete unused create_runners_iam_instance_profile

main.tf, template/runner-config.tpl, variables.tf
Similar to https://github.com/npalm/terraform-aws-gitlab-runner/pull/140, limit the docker machine ssh ingress access to only the runner via security groups instead of cidr ranges.
I kept backwards compatibility by making this feature optional (defaults to false) as I do not know if people actually need external SSH access to the docker machines. @npalm Do you think external SSH access is necessary? If it doesnt make sense, we could remove the CIDR based security rule and simply the code. Otherwise, this should work to support both cases.
No
=> Add option to limit docker machine ssh ingress access to only the runner

README.md, _docs/TF_MODULE.md, cache/README.md, cache/_docs/TF_MODULE.md, cache/main.tf, cache/variables.tf
Fix bad type and possible race condition/intermittent failures. 
The cache module would fail on some of our developer's laptops. Currently, you optionally call `data.aws_caller_identity` if `create_cache_bucket` is set to true. `create_cache_bucket` defaults to `bool` true but has an improper type of `string`. This likely doesn't matter bc of loose automatic terraform type-conversion but should get fixed.  You then optionally decide to prefix the bucket with the account-id if `cache_bucket_name_include_account_id` is set to true. `cache_bucket_name_include_account_id` has a correct bool type. There is a chance for these invariants to not line up - i.e. dont create the cache bucket but ask for it to add the account_id to the bucket name.
_That said, in our case, we were leaving these as …
=> fix type create cache bucket

README.md, _docs/TF_MODULE.md, examples/runner-docker/main.tf, main.tf, outputs.tf, policies/instance-eip.json, template/eip.tpl, template/user-data.tpl, variables.tf
allow assignment of an elastic IP for the gitlab runner instance (mostly useful if it is run with a public IP
NO. Feature is disabled by default
Documentation has been updated.
=> Allow assignment of Elastic IP

examples/runner-docker/README.md, examples/runner-docker/_docs/TF_MODULE.md, examples/runner-docker/variables.tf
Docker runners artifact upload fails with error described in:
https://gitlab.com/gitlab-org/gitlab-runner/issues/4083
The default value of the `gitlab_url` variable should be `https://gitlab.com` and not `https://www.gitlab.com`.
See #169
NO
Tested the change using docker-runner using the value `https://gitlab.com` in `runners_gitlab_url`.
updated:
* examples/runner-docker/_docs/TF_MODULE.md
* examples/runner-docker/README.md
=> Change default for gitlab_url to https://gitlab.com

README.md
Fixed missing double quotes in gitlab_runner_registration_config
Simply a missing closing double-quotes
NO
No need verification.
=> Fixed missing double quotes

README.md, _docs/TF_MODULE.md, variables.tf
Fixed some typos in the description for the cache_bucket variable.
NO
Fixed some typos in the description for the cache_bucket variable.
=> Fixed typos cache bucket

README.md, _docs/README.md, _docs/TF_MODULE.md, bin/remove-runner.sh, cache/README.md, cache/_docs/TF_MODULE.md, main.tf, template/gitlab-runner.tpl
This is primarily set up to resolve the issues I pointed out in #163. This creates a one-line script that sends a `DELETE` request to the proper Gitlab endpoint to remove this runner from Gitlab. I'm also removing the key from SSM at the same time, since the key is now unable to be used in the future. 
NO, I don't think?
I've been verifying this by pointing my usage of this module to my fork/branch and then trying doing apply/destroys. At this point, it seems to be working as expected, but I'd love to see someone else validate it on their own.
I've added what I help are appropriate comments - let me know if I should add more robust documentation elsewhere, but this doesn't seem to have a place to put it.
~~Currently, I'm running into problems around the use of SSM caching of the runner …
=> Remove runner on instance shutdown.

README.md, _docs/TF_MODULE.md, cache/README.md, cache/_docs/TF_MODULE.md, main.tf, variables.tf
Currently, it's possible to `terraform apply` an update to a number of aspects of the Runner, but not see them actually reflected in the running resources because of how AWS works. For example, if I need to change the Runner registration token, you can apply those changes, but the actual Runner resources won't update on their own to pick up that change.
This is due to the fact that in both AWS and Terraform, EC2 Launch Configurations are a separate resource from the EC2 Autoscaling groups. Many/most changes to how the Runners are configured are set as part of the Launch Config, and while Terraform will dutifully create a new Launch Config and update the ASG to use it, the ASG will only apply the new config to _new_ instances, and will not push the update to any currently-running instances …
=> Forcing updates of Instances on Config change.

ci/bin/cancel-spot-instances.sh
While I was working with automating the creation and destruction of Gitlab runners, I noticed a couple issues with the `cancel-spot-instances.sh` script. The first was that we were assuming that `bash` would be installed on the system, in addition to `jq` and `aws`, which isn't true by default in Alpine Linux and other Busybox-based systems where people tend to run CI tasks. Second, if you apply and then immediately delete a set of runners, they won't have any Spot instances or requests to tear down, which causes the script to fail, even though it had nothing to do and should just exit gracefully.
I'm open to removing the check for `aws` and `jq` if we don't want that here. I just added it since the script will fail if either of them is absent, so that line will instead provide a helpful …
=> Improving Spot Cancelation script.

README.md, main.tf, tags.tf, variables.tf
Solves #175. We need to apply tags only to the EC2 resources for an application that manages resources by tag.
NO
Readme updated
=> Added agent- and runner-only tags

README.md, _docs/TF_MODULE.md, main.tf, template/runner-config.tpl, variables.tf
Without specifying an EBS-optimized, AWS defaults to `false`.  This adds an EBS-optimized configuration option to both the runner instance and runners. Defaults them both to `true` (both the default GitLab runner instance type, `t3.micro`, and the default docker machine runners instance type, `m5a.large`, use EBS-optimized by default anyways, even though the instances are currently set to disabled).
NO
=> Add inputs for EBS-optimized

variables.tf
Bump runner version from `12.6.0` to `12.7.1`
See [GitLab ChangeLog](https://gitlab.com/gitlab-org/gitlab-runner/blob/master/CHANGELOG.md)
NO
Nothing
Nothing
=> Bump gitlab runner version to 12.7.1 from 12.6.0

README.md, _docs/README.md, template/gitlab-runner.tpl, template/logging.tpl, variables.tf
This PR addresses #177. It changes the user data scripts such that they test whether the distribution is Amazon Linux 2 and, if so:
- install docker from the "extras" bundles;
- use systemd to start docker and awslogsd;
NO
Successully deployed GitLab runner and end executed a job using `ami_filter = { name = ["amzn2-ami-hvm-2.0.*-x86_64-ebs"] }`.
I updated the README in `_docs/README.md` and manually updated the README.md in the root  folder. 
The script `ci/bin/autodocs.sh` failed for me with error messages from terraform-docs like: `Failed to read module directory: Module directory /tmp/terraform-docs.YY7w3Rt7Up does not exist or cannot be read.`
=> Support Amazon Linux 2

.github/pull_request_template.md, README.md, _docs/TF_MODULE.md, cache/README.md, cache/_docs/TF_MODULE.md, ci/bin/autodocs.sh, ci/bin/run-local.sh, ci/bin/terraform-docs.sh, examples/runner-default/README.md, examples/runner-default/_docs/TF_MODULE.md, examples/runner-docker/README.md, examples/runner-docker/_docs/TF_MODULE.md, examples/runner-pre-registered/README.md, examples/runner-pre-registered/_docs/TF_MODULE.md, examples/runner-public/README.md, examples/runner-public/_docs/TF_MODULE.md
As suggested by @chludwig-haufe  terraform docs now supports terraform 0.12. The work around can be removed. 
NO
Generate docs.
=> Update terraform-docs to support 0.8.x

main.tf
=> #187 - fix double comma in tag list for docker machine

examples/runner-docker/README.md, examples/runner-docker/main.tf
In runner-docker example, there is a ssh keys generation but these keys are not used in runner module. We can't connect to ec2 instance.
NO
runner-docker example
=> Complete docker example with ssh keys usage

README.md, _docs/TF_MODULE.md, examples/runner-docker/README.md, main.tf, variables.tf
Add a variable to allow setting a permissions boundary policy on newly created IAM roles.
No.
Running `terraform apply` both with `permissions_boundary` set and without.
> Please ensure you update the README in `_docs/README.md`. The README.md in the root can be updated by running the script `ci/bin/autodocs.sh`, requires `terraform-docs` version 0.8+
Done.
=> Add permissions boundary

README.md, cache/main.tf, cache/variables.tf, kms.tf, logging.tf, main.tf, policies/instance-logging-policy.json, policies/instance-secure-parameter-role-policy.json, policies/kms-policy.json, policies/service-linked-role-create-policy.json, variables.tf
This change allows a user to override the AWS ARN (which to defaults to
the most common use case of "arn:aws") in order to allow one to use this
module in the AWS GovCloud/China regions. This can be done by setting
the value of the arn_format variable to "arn:aws-us-gov"/"arn:aws-cn"
respectively.
This should address the policy changes necessary for this previously opened PR here:
https://github.com/npalm/terraform-aws-gitlab-runner/pull/110
NO
I have successfully used my fork to deploy within GovCloud.
This new variable has been documented in README.md
=> Parametrize the AWS ARN for policies

README.md, main.tf, variables.tf
This change allows us to enable SSM on the docker-machine instances similar to how we can enable it for the runner agent using variables.
NO
We have successfully used our fork to deploy and connect to the docker-machines through SSM.
This new variable has been documented in README.md.
=> Add SSMManagedInstanceCore policy to the docker machine role.

README.md, kms.tf, variables.tf
Add a kms alias to the kms key (for log group).
NO
One runner instance with spot runners
=> Add a kms alias to kms key

README.md, main.tf, variables.tf
Fixes #259 
I'm running a cheap 💰  cluster and noticed an additional cost being introduced because the Terraform module for `auto_launch_configuration` 
sets `enable_monitoring: true` by default. 
There was no variable yet in the module to disable `EC2 Detailed Monitoring` and revert it back to basic monitoring. This PR adds a variable to control that setting. 
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_configuration#enable_monitoring
No
I have verified it in my own project (private Gitlab), which is built on the `runner-default example`, by using:
```
source = "git::https://github.com/jessedobbelaere/terraform-aws-gitlab-runner.git?ref=add-variable-disable-detailed-monitoring"
```
And doing a few Terraform apply's where the variable is enabled or …
=> Add variable to disable EC2 detailed monitoring

README.md, main.tf, modules/cache/README.md, modules/cache/main.tf, modules/cache/variables.tf, variables.tf
Hey Niek! 
Feel free to reject this if you don't think it's useful :) I needed it to quickly recreate the module multiple times without having to change the bucket name in every run 
(as a result of testing some cloud-init userdata changes in our setup).
This change adds the option to append a random string suffix to the S3 bucket name. 
As bucket names can only exist once, it's not possible to destroy the module and reinstall after without config changes as the previously used bucket name is not free for use anymore after teardown.  By adding a random string to the bucket name this problem is solved.
This can also be useful if you want to use the same configuration for multiple regions.
NO - Not if `cache_bucket_set_suffix` is not set to true.
Not yet! Will test later this week. 
^ Is …
=> Random suffix to s3 bucket

README.md, main.tf, variables.tf
Ability to attach additional policies is quite helfpuf, for example if one would like to use gitlabrunner to build golden AMIs.
I have tested proposed changes and was able to deploy and attach additional policy successfully.
=> Add option to attach additional policies to the runner agent instance

README.md, main.tf, variables.tf
Provide support for user defined IAM policies to be attached to the docker machine runners. This allows pipelines that need to access IAM resources to have their permissions defined by the docker machine profile.
NO
Ran the ci verification steps. Also tested with my desired use case, attached a custom policy to the docker machine instance role.
Documentation was updated.
=> Allow custom policies to be attached to the docker machine profile

.github/workflows/verify.yml, README.md, ci/bin/terraform.sh, modules/cache/README.md, variables.tf
- update docker macine to latest gitlab mainated version
- update runner ami to ubuntu 20.04
- update gitlab runner default version to latest (13.7)
NO
=> Update default versions

examples/runner-docker/_docs/TF_MODULE.md, examples/runner-docker/main.tf, examples/runner-docker/variables.tf, security_groups.tf, variables.tf
Just a small update to be able to customize the security groups description for both gitlab runner and docker machine instances.
NO
Verified on runner-docker example
Documentation updated in runner-docker example
Please ensure you update the README in `_docs/README.md`. The README.md in the root can be updated by running the script `ci/bin/autodocs.sh`, requires `terraform-docs` version 0.8+
=> Feat: Support Security Group custom description

template/eip.tpl
Fix for #279 
No
Default example with eip enabled
=> fix: failing pip install for assigning eip

variables.tf
Upgrade the Gitlab runner default version to the latest stable 13.8.0
NO
Verified with the default example.
=> Upgrade Gitlab runner version

modules/cache/main.tf
This PR entirely restricts the public access to the cache bucket. Currently, the bucket is private via ` acl    = "private"` but objects might be set to public via an owner (not likely but AWS shows a arning, so this is merely a security/warning fix). This is shown as a warning in the AWS UI (see images - sory for german UI). The PR resolves these warnings. Functionality should not be affected as all runners have an access policy for the bucket.
NO
Used in my deployment.
No documentation needed, buckets are already private as default and its not changeable.
=> Restrict public access and public objects for cache bucket

README.md, examples/runner-default/versions.tf, examples/runner-docker/versions.tf, examples/runner-pre-registered/versions.tf, examples/runner-public/versions.tf, main.tf, modules/cache/main.tf, versions.tf
- Add tagging to aws_iam_policy supported by AWS provider 3.35
- Fix #315 
NO, upgrade to aws provider 3.35 required
Default example
=> feat: Add tags to aws_iam_policy

main.tf
the resource "aws_iam_instance_profile" "instance"  has not tags, we need the tags for policy verification purposes
=> fix: add tags for instance profile

main.tf, variables.tf
As described in #333 it is useful to have special tags to add to the `aws_iam_role` to allow tag based authorization. As these tags are needed on the role only I introduced a new variable `role_tags` for them.
NO
Plan checked
```
+ tags                  = {
+ "Environment"                  = "prod-gitlab-ci-runner-non-terraform"
+ "Name"                         = "prod-gitlab-ci-runner-non-terraform"
+ "allowReadPlatformCredentials" = "gitlab-ci-runner"     # <<< role_tags
+ "app"                          = "runner"
+ "environment"                  = "prod"
+ "service"                      = "gitlab-ci"
+ "team"                         = "sales"
```
=> Add `role_tags` to support tag based authorization (#333)

.gitignore, main.tf, tags.tf
null_data_source should not be used anymore.
Terraform locals should be used instead.
A warning is displayed with terraform 1.0.1.
NO
=> fix: replace deprecated null_data_source with locals

main.tf, variables.tf
Parametrize usage of Gitlab runner agent instance AWS metadata service  in launch configuration. This enables control of instance AWS IMDSv1 and IMDSv2 options and enables mitigation of AWS Security Hub issue related to IMDSv1 being enabled (EC2 instances should use Instance Metadata Service Version 2 (IMDSv2))
NO
Launch configuration AWS metadata service options change based on input variables given to the module.
=> feat: Parametrize runner instance launch configuration metadata options

locals.tf, main.tf, template/gitlab-runner.tpl, template/runner-config.tpl, variables.tf
[GitLab runners support reporting errors to Sentry](https://docs.gitlab.com/runner/configuration/advanced-configuration.html#the-global-section) which makes troubleshooting a bit easier than going through system logs.
NO
Tested in our live GitLab runners. Did not run the examples.
On first apply it sets the Sentry DSN to empty string which pretty much is the default behaviour. It also creates the SSM parameter in which you should set the **legacy version** of your Sentry DSN and on the next startup it will use that DSN.
Btw when I ran `pre-commit run` it gave me following output which I find kind of suspicious.
```
Terraform fmt........................................(no files to check)Skipped
Terraform validate with tflint.......................(no files to check)Skipped
Terraform …
```
=> Support for setting Sentry DSN

main.tf, variables.tf
AWS recommend that we should use launch templates instead of launch configurations.
With the launch template, we can now use a CMK for storage encryption. Globally, launch template allows
to configure more things than the launch configuration.
NO
=> feat: replace launch configuration with launch template

main.tf, security_groups.tf
Launch template is named based on `runners_name`variable. It seems to be an error because this launch template is used to deploy the agent runner not docker machines. Tell me if i'm wrong.
Moreover security groups have tag `Name` with `local.name_sg`but the `name_prefix` do not use this local. Maybe it is an oversight ?
NO, default values not change
Minor changes
=> [Proposal] Use better ressources names

locals.tf, main.tf, variables.tf
I added a new key `name_iam_objects` in `overrides` map to rename all IAM objects (instance profile, role and policies).
NO, default values not change
Ok
=> [Proposal] Add IAM objects name override option

main.tf
Add documentation why iam:PassRole policy is needed. See #368 
no
Comment only. No code change, no verification
=> Document reason for iam:PassRole

main.tf, policies/instance-docker-machine-policy.json
The police iam:PassRole was not limited to a certain role ARN. This caused security warnings by ScoutSuite. This PR limits the policy to the role passed to the docker machine instances. See #368 
No
Tried this configuration in the Hapag-Lloyd Gitlab CI without problems.
=> Limit iam:PassRole to the role passed

bin/remove-runner.sh, main.tf, versions.tf
If the AWS provider assumes a role, it is not possible to use the AWS CLI to interact with the cloud resources as the CLI does not assume the role automatically. The removal of the runner agents from Gitlab fails.
This PR moves the whole script to remove the runner agent into the Terraform code and does not use the AWS CLI.
Closes #371 
No
Still pending.
=> Remove runner agents if provider assumed a role

.pre-commit-config.yaml, README.md, main.tf, template/runner-config.tpl, variables.tf
Make check interval configurable for the runner in order to reduce load on gitlab API
NO
=> Make check interval configurable for the runner

README.md, locals.tf, main.tf, variables.tf
As [Docker](https://docs.docker.com/docker-hub/download-rate-limit/) introduced rate limiting we should set a Docker registry mirror. This was possible via `docker_machine_options`. I think it makes sense to make this explicit using a dedicated variable.
Solves a part of #393 
Closes #270 
Yes, if the option `engine-registry-mirror` is used within the `docker_machine_options`. If so move the mirror URL to the new variable `runners_docker_registry_mirror`
Checked all combinations of `runners_docker_registry_mirror` and `docker_machine_options`.
=> feat!: Add variable for Docker registry mirror

README.md, outputs.tf
Add a `runner_launch_template_name` output to the module to return the
name of the launch template that's managed.
NO
Base example; my own existing deployment
=> Add launch template name to module outputs

main.tf
The documentation references being able to use "kms_key_id" in a dictionary in order to be able to encrypt the EBS volume.  This did not work, and the actual value was \`kms_key_id\`.  Corrected that.
NO
Modified locally and ran - the ARN was successfully found and updated.
=> Removed extra backticks.

.pre-commit-config.yaml
Add the `-recursive` argument to `terraform fmt` to format all files in this repository.
Fixes part of #423
No
Ran pre-commit and verified that the files were formatted.
=> build: Format Terraform files recursively

LICENSE, README.md, examples/runner-default/main.tf, examples/runner-docker/main.tf, examples/runner-pre-registered/main.tf, examples/runner-public/main.tf, main.tf, variables.tf
Deprecates `subnet_ids_gitlab_runner` and `subnet_id_runners` and introduces `subnet_id` to make the module more readable as explained in #411 and #419. Thus it it no longer possible to place the runner and the executors in different subnets. For a resilient configuration deploy the module once per availability zone.
Closes #419
No, but migration should be done.
Replace `subnet_ids_gitlab_runner` and `subnet_id_runners` by `subnet_id`. Please notice that it is no longer possible to place the runner and executors in different subnet. For a resilient configuration, I suggest to deploy the module once per availability zone.
Checked the following:
- config.toml checked for subnet value using `subnet_id`. Success. Correct subnet used.
- Check that the Runner is created in correct subnet using …
=> refactor: Harmonize subnet variables

template/gitlab-runner.tpl
This PR is based on the work of patramsey as described in #230.
Gitlab Runner checks the validity of the token stored in SSM. In case the token is invalid a new one is requested.
Closes #230 
No
The following verifications were done:
- Change the registration token manually, kill the Runner manually. I expect to get a new Runner registered at Gitlab. Success.
- Delete the Gitlab Runner from Gitlab and kill the Runner EC2. Expect to get a newly registered Runner. Success.
- Check Cloudwatch logs to see the result of the verification call: 403. Success.
=> feat: Request new Runner token if invalid

template/runner-config.tpl
Gitlab runner uses text-based logging by default. However due to https://gitlab.com/gitlab-org/gitlab-runner/-/merge_requests/179 all of the logs include tty coloring codes which make logs pain to process or read.
Since this module offers logging to cloudwatch by default anyways this simple change will make the log readable and usable in CloudWatch.
NO. Will be handled by Gitlab runner instance refresh.
Changed manually on the server. Then tried this change in my environment.
No changes needed.
=> Switch logging to JSON

README.md, versions.tf
Locking AWS TF provider to 3.x due to breaking chaninges in 4.x. Fixes for 4.x see #444 and #445
NO
=> fix: Lock AWS provider to 3.x

README.md, main.tf, modules/terminate-instances/README.md, modules/terminate-instances/cloudwatch.tf, modules/terminate-instances/iam.tf, modules/terminate-instances/lambda/lambda_function.py, modules/terminate-instances/main.tf, modules/terminate-instances/outputs.tf, modules/terminate-instances/variables.tf, template/gitlab-runner.tpl, template/runner-config.tpl, variables.tf
This introduces an Auto Scaling Group instance termination lifecycle
hook using Lambda and related resources. The Lambda function is a Python
script that is triggered when the persistent runner instance in the ASG
is terminated. The function receives the instance ID of the "parent"
runner and queries for spawned instances that it launched to terminate.
Additionally, it will check for other "orphaned" instances that have a
`gitlab-runner-parent-id` tag that doesn't match an existing instance. This
resolves the issue where spawned instances could be orphaned when their
parent runner is terminated.
This feature is disabled by default.
The user data script is updated to provide the 'parent' instance ID as a
tag named 'gitlab-runner-parent-id' on spawned instances.
A new sub-module is provided …
=> Add ASG lifecycle management Lambda function

template/gitlab-runner.tpl
Currently the gitlab runner user data will try to download/run install script then install. This change will allow alternative installation via userdata_pre_install
NO
Tested without issue using default install and when already installed. 
pre-commit run fine, no change to terraform inputs or docs required.
=> feat: Skip runner download and install if already installed

.gitignore
Ignore the `builds/` directory which contains the zipped AWS Lambda function. Add the directory to the `.gitignore` to make sure it is not checked in by accident.
No
None
=> chore: git ignore `builds/`

modules/terminate-instances/main.tf
https://github.com/npalm/terraform-aws-gitlab-runner/issues/464 reports that the `architectures` argument was added in the AWS provider 3.61.0 and this module specifies 3.35 as a minimum.
The `architectures` argument is optional and defaults to 'x86_64' anyway.
This removes it so that it's compatible with the older AWS provider.)
NO
Verified using the _runner-default_ example
N/A
=> fix: terminate lambda: don't specify architecture

.pre-commit-config.yaml
`pre-commit` fails with `The unauthenticated git protocol on port 9418 is no longer supported`. Switch to https to fix that.
No
Run `pre-commit`.
=> chore: switch to https for pre-commit

.pre-commit-config.yaml, main.tf
Join the Docker tmpfs volumes in the `runner-config.tpl` with a newline character instead of `,`. This gives the correct syntax as explained in the mentioned issue.
```
[runners.docker.services_tmpfs]
"/var/lib/mysql/" = "rw,noexec","/var/lib/postgresql/data" = "rw,noexec"
```
Closes #479 
No
Checked the plan for multiple volumes.
=> fix: join the docker volumes with \n instead of ,

main.tf
We use on-demand-price and recently upgraded from 4.35 to 4.41.1. On every run we see:
```
~ instance_market_options {
+ spot_options {}
}
```
... causing a complete rebuild. This fixes that problem with a dynamic block on `spot_options`
NO
I verified using runner_instance_spot_price    = "on-demand-price" and "0.18". Both work as expected.
None.
=> fix: Use dynamic block to avoid endless churn on spot_options block

main.tf, template/runner-config.tpl
One method to support adding AuthenticationType = "IAM" whilst ensuring no changes to configuration for earlier versions.
Only adds it in if the major version of the runner is 15 or higher.
NO
Tested with versions 14 & 15 to confirm the user-data only sees this change if version 15.
=> 471 add AuthenticationType

template/runner-config.tpl, variables.tf
This PR adds the AuthenticationType for [runners.cache.s3]. Not specifying an AuthenticationType is a [deprecated](https://gitlab.com/gitlab-org/gitlab-runner/-/issues/28171) feature and breaking change for GitLab 15.0.
The AuthenticationType can either be `iam` or `credentials`, and this PR allows the user to specify which AuthenticationType they use as a variable. Previously, this would default to iam credentials, so I maintained the default authentication method in `variables.tf`
No
When the runner was manually updated, the change only impacts the actual launch template of the child runners. All future spawns will be using the correct auth type.
=> Add AuthenticationType for [runners.cache.s3]

template/gitlab-runner.tpl
This PR updates the URL used for the `PARENT_INSTANCE_ID` variable so that it now points to the AWS IMDSv2 endpoint. 
Using the old URL caused an empty `gitlab-runner-parent-id` tag to be added to all runner instances created by agents, which broke the Lambda function for terminating stray runner instances.
Closes #496 
NO
Successfully tested in private AWS account.
=> fix: use IMDSv2 url when setting PARENT_INSTANCE_ID

main.tf, template/runner-config.tpl, variables.tf
Adds the missing parameter ` clone_url` to the `config.toml` of the runner. In case the default clone URL from the GitLab project is not accessible from the runner's infrastructure (e.g. private DNS), the `clone_url` can be used to specify a different one (e.g. replace the private DNS entry by a public IP address).
Check the [configuration docs for the runner](https://docs.gitlab.com/runner/configuration/advanced-configuration.html#the-runners-section).
No.
I check this within the Hapag-Lloyd GitLab Runner infrastructure.
=> feat: add `clone_url` to `config.toml`

locals.tf, main.tf, modules/cache/main.tf, modules/cache/versions.tf, modules/terminate-instances/cloudwatch.tf, modules/terminate-instances/main.tf, modules/terminate-instances/versions.tf, variables.tf, versions.tf
aws_cloudwatch_event_rule is missing tags argument.
Others changes are related to tflint errors.
NO
=> feat: Add tags parameter to aws_cloudwatch_event_rule resource + linting

README.md, main.tf
As described in #298 the cache module has to be applied separately before creating the Runners. Terraform complains about
```
Error: Invalid count argument
on ..\..\..\terraform-aws-gitlab-runner\main.tf line 323, in resource "aws_iam_role_policy_attachment" "docker_machine_cache_instance":
323:   count      = var.cache_bucket["create"] || local.bucket_policy != "" ? 1 : 0
The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.
```
This PR always adds the policy to get rid of the error message during `apply`. As far as we know there is no use cases deploying this module without a cache. …
=> fix: always add the cache policy

main.tf, modules/cache/main.tf, modules/cache/outputs.tf, modules/cache/variables.tf, outputs.tf
Marks `create_cache_bucket` deprecated to simplify the cache module. In case no cache should be created it is better to not call this module instead of setting the variable to `false`. In this case the module does nothing.
Closes #525 
In case `create_cache_bucket` was set to `false`: remove the whole module call as it does nothing. Otherwise you should remove the deprecated variable.
=> refactor!: remove usage of `create_cache_bucket`

locals.tf, main.tf, tags.tf, template/runner-config.tpl, variables.tf
This PR checks the version of the docker machine and adds the Name tag if it is not done by the driver itself. It also removes the second `Name` tag from the `amazonec2-tags` in the `config.toml`. In consequence it is no longer possible to change the Name of the Runners as the `Name` tag is now added by the docker-machine driver (for versions >= 0.16.2).
`docker_machine_version` >= 0.16.2 automatically adds the Name tag to the EC2 instances. Adding another Name tag here causes the EC2 creation process to fail.
To be able to configure the name, `var.overrides["name_docker_machine_runners"]` is added as prefix to the name of the docker machine which is used as name for the EC2 instance by the driver.
The main logic was taken from https://github.com/hashicorp/terraform/issues/22688#issuecomme …
=> feat: do not add a the Name tag for docker+machine >= 0.16.2

main.tf
Fixes an error applying the cache module. As a `count` was introduced, we have to use an index to access the module's result.
No
None
=> fix: access cache module via index

tags.tf
Docker machine instance not starting caused by to long names. Enforced the max length.
fix: #536 
NO
=> fix: Too long host names for docker machines

variables.tf
use latest Gitlab runner version by default
NO
=> chore: use latest Gitlab runner version by default

main.tf
In case the module does not create the cache and `var.cache_bucket["policy"]` is empty, the module can't be deployed as explained in  https://github.com/npalm/terraform-aws-gitlab-runner/pull/528#issuecomment-1234004003.
This PR makes sure to add the policy only if it exists.
No.
=> fix: do not add the cache access policy if there is none

variables.tf
This PR makes sure that the maximum hostname length of a Runner does not exceeds the limit of 64 characters. In case the maximum length is exceeded the runners can't be created and no jobs will be processed.
- the user defined part of the hostname set by `var.overrides["name_docker_machine_runners"]` is limited to 28 characters.
- in case the `var.overrides` feature isn't used, the name is created based on `var.environment` plus a `-docker-machine` suffix. If the name of the environment is too long we simply substring everything to 28 characters.
Closes #536 
No
=> fix: ensure a maximum Runner hostname via override length of 64 characters

main.tf, template/user-data.tpl, template/yum_update.tpl, variables.tf
This will allow for runners to be launched from a known working AMI and not have yum update introduce unexpected issues.
The default is to run the yum update as is current but allows for disabling.
NO - Existing behaviour not changed
Tests based on Example - Spot Runner - Default without issue.
=> feat: Skip yum update

kms.tf, logging.tf, main.tf, policies/instance-logging-policy.json, policies/instance-secure-parameter-role-policy.json, policies/kms-policy.json, policies/service-linked-role-create-policy.json, variables.tf
The `arn_format` used for US Gov and China can be calculated with `aws_partition`. Thus the parameter in the module is obsolete, marked as deprecated and should by removed with the next major release.
No, but you should remove the `arn_format` parameter from the module call as it is no longer in use.
=> refactor: remove `arn_format`

locals.tf, logging.tf, main.tf, outputs.tf, variables.tf
Closes #571 
NO
Verified in my local environment
=> Allow custom runner agent IAM role

README.md, main.tf, template/runner-config.tpl, variables.tf
Allow setting a configurable parameter to set the EBS volume type on the instances spawned to run jobs. This defaults to gp2, and is not required
Fixes https://github.com/npalm/terraform-aws-gitlab-runner/issues/578
A few sentences describing the overall goals of the pull request's commits.
NO
=> feat: Support volume type configuration

main.tf
Closes #561 
NO
Done:
EC2 runner working correctly in my environment for several days now.
On the EC2 Launch Template, User data is visible as b64 + gzip encoded.
On the EC2 instance panel, User data displays as "No user data" for some reason.
=> Zip user_data

template/gitlab-runner.tpl
This PR ensures that the `config.toml` is complete before its first usage by the GitLab Agent.
Remark: You will still see an initialization error of the Runners first, but this heals some seconds later without doing anything.
```
NAME                                                         ACTIVE   DRIVER      STATE   URL   SWARM   DOCKER    ERRORS
runner-b8pa-z3w-G-E-TEST-eu-central-1c-2338672298-9deafea1   -        amazonec2   Error                 Unknown   MissingParameter: The request must contain the parameter InstanceId
```
Closes #450 
No
Created 3 new agents with the default Hapag-Lloyd setup and the current version of the module --> dangling machines were created.
Created 3 new agents with the default Hapag-Lloyd setup and this version --> there are no dangling machines. Jobs …
=> fix: ensure a complete `config.toml` before starting the GitLab Agent

template/runner-config.tpl
Since #544 was merged in, `runners_pull_policies` is used to set the runner's `allowed_pull_policies` instead of `pull_policy`. That is confusing, and it changes the behaviour of the directive and prevents setting the default pull policy for the runner.
This change switches back to using `runners_pull_policies` to set the runner's `pull_policy`, while still allowing for multiple policies to be defined.
NO
I have verified that the correct `pull_policy` directive is now set on the runners.
=> fix: Set pull_policy instead of allowed_pull_policies

locals.tf
Fix missing `:` - `aws_iam_role_instance_arn` is invaild without this fix.
NO
Found, fixed and checked on my own Gitlab cluster.
=> Fix runner_agent_role_arn

logging.tf, main.tf
Fixups relating to #572 
When a custom role is specified we should also have ability to avoid attaching any additional policies to the role, in the case when the custom role already has enough permissions (and may be at/near the 20 attached policies limit).
Also disable creating the instance profile when we aren't also creating the role.
This means multiple copies of the runner module can be made safely with the same custom role and without duplicating the instance profile. Though duplicating the instance profile doesn't cause any errors it is unexpected, in the AWS IAM console you can only see a single instance profile for a role. Allocating 2 or more seems to have no effect and Terraform doesn't seem to pick this up as an error condition either.
NO
I've manually tested the changes in my …
=> Allow custom runner agent IAM role fixups (#572)

.github/workflows/ci.yml, .github/workflows/update_docs.yml, README.md
The workflow was not running in case the PR was created from a foreign repository. The checkout of the branch didn't succeed.
The TF docs are now generated in the release branch if a commit is pushed.
=> ci: fix the TfDocs creation in feature branch

README.md, modules/cache/variables.tf, variables.tf
Adds a few sentences and examples to make clear what policies are needed for a customer defined KMS key.
Closes #610 
No.
No verification. Documentation only.
=> docs: detail the policies for KMS keys

.github/workflows/stale.yml
Adds a workflow to mark issues and PRs after 60 days as stale and auto-close them after another 15 days. This helps to remove everything we are not actively working on.
=> chore: mark PRs and issues as stale and auto-close them

.github/dependabot.yml
This PR fixes the Dependabot setup:
* add missing example directory `/examples/multi-region` to Dependabot
* use weekly updates instead of daily updates for examples
* use correct `package-ecosystem` to allow Dependabot to update the workflows
=> chore: fix Dependabot configuration

.github/workflows/ci.yml
Workflows are failing at the moment with "403 Rate Limit" error when running TfSec. Instead of waiting for Dependabot, I bump the version manually.
[Version 1.3.0](https://github.com/aquasecurity/tfsec-pr-commenter-action/releases/tag/v1.3.0) fixes the problem with the rate limiting.
=> ci(deps): bump TfSec commenter to 1.3.1

.github/FUNDING.yml
Correct syntax for `FUNDING.yml` is: `github: userid`. See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
=> chore: fix syntax error in `FUNDING.yml`

outputs.tf
Adds a new output `runner_user_data` to the module to show the value of the `user_data` script. Especially useful as the the script is now gzipped.
Closes #321 
No
No verification done. One output added only.
=> feat: add user data of agent to outputs

.github/workflows/lint_pr_title.yml
Adds a new workflow action which lints the title of the PR. This is to make sure that we have commits adhering to the semantic commit rules only. Otherwise Release-Please is not able to determine the next version number and will not create a release.
=> ci: validate PR title

variables.tf
Adds a custom validation to the `var.overrides["name_docker_machine_runners"]` variable and makes sure that valid characters are used only. Otherwise the executor (docker+machine) instances can't be created and no jobs from Gitlab are processed.
Related to #447 
No.
Still pending
=> feat: add validation rule for docker machine name

README.md
Amends the documentation and describes what to do in case of a Terraform error if the cache S3 bucket is self managed. It needs a separate Terraform run to apply the changes of the cache module first.
Closes #590
=> docs: add handling instructions for self managed cache

.github/workflows/stale.yml
All labels in this project starts with a lowercase letter, except the one for `Stale` issues. This PR streamlines the label used to mark stale issues and PRs. The label used is `stale`
=> ci: use lowercase `stale` label

.github/dependabot.yml
Tests are written in Go and thus the Go dependencies should be updated automatically to the newest version. This PR changes the Dependabot configuration to allow automatic updates.
=> ci: enable Dependabot updates for Go

main.tf, policies/instance-logging-policy.json
In some cases Terraform reports an error message and can't create the log group for the runner agent. The reason is, that the Cloudwatch agent running on the EC2 instance is already up and creates the log group before Terraform does it. This should never happen.
Attention: The policy `logs:CreateLogGroup` can't be removed. It shouldn't be needed by the Cloudwatch agent, but if it is not attached, no log streams are created within the log group and thus no logs are visible.
No
Module deployed and verified that the log group/stream is populated with logging data.
=> fix: create the log group before creating the runner agent

.github/dependabot.yml
Depdabot configuration contains [errors](https://github.com/npalm/terraform-aws-gitlab-runner/pull/636/checks?check_run_id=10498044900), commit_message -> commit-message
NO
CI
=> ci: fix dependabot configuration

.terraform.lock.hcl, examples/runner-default/.terraform.lock.hcl, examples/runner-default/versions.tf, examples/runner-docker/.terraform.lock.hcl, examples/runner-docker/versions.tf, examples/runner-multi-region/.terraform.lock.hcl, examples/runner-multi-region/versions.tf, examples/runner-pre-registered/.terraform.lock.hcl, examples/runner-pre-registered/versions.tf, examples/runner-public/.terraform.lock.hcl, examples/runner-public/versions.tf, versions.tf
To get reproducable results the versions of the providers used in Terraform are fixed. This way we always know which provider was used when the example was applied.
No.
None. Changes in examples only
=> chore: pin Terraform provider versions with lock file

variables.tf
This PR updates the docker+machine to the newest version. The fixed bug relevant here is:
> With Docker 23.0.0 release (which happened today), installation of Docker doesn't create an /etc/docker directory
> anymore by default. It needs to be done manually.
> At the same time, Docker Machine's provisioning for some of the supported distributions assumes that it will be there by
> default and starts writing key/certificates files into that directory immediately. Which fails with
>
> `ERROR: tee: /etc/docker/ca.pem: No such file or directory`
This fixes https://gitlab.com/gitlab-org/ci-cd/docker-machine/-/issues/98
NO
Updated in our environment which fixed the issue
=> fix: bump docker machine version due to bug

template/gitlab-runner.tpl, variables.tf
Only download and install Docker Machine binary when executor is `docker+machine`. This prevent an unnecessary download of the binary when the executor is `docker`.
Boy scout: removed all the "\`echo $[variable]\`" instances, seems unnecessary and spawns a subshell for each of these calls.
NO
```bash
$ which docker-machine
/usr/local/bin/docker-machine
```
```bash
$ which docker && which docker-machine
/usr/bin/docker
which: no docker-machine in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin)
```
```bash
❯ tfplan
╷
│ Error: Invalid value for variable
│ 
│   on gitlab_runner.tf line 52, in module "runner":
│   52:   runners_executor = "shell"
│     ├────────────────
│     │ var.runners_executor is "shell"
│ 
│ The executor currently supports `docker+machine` or `docker`.
│ 
│ This was …
```
=> chore: only install Docker machine when executor is docker+machine

main.tf
Sets the lifecycle prefix correctly based on whether the cache is shared or not.
For more context see validation in #539.
NO - users of a shared cache should finally get a correct lifecycle prefix! 🚀 
```hcl
cache_shared = false
```
Result:
```hcl
cache_shared = true
```
Result:
Closes #539
=> fix: set correct lifecycle prefix for shared cache

.github/workflows/slash_ops_commands.yml, .github/workflows/slash_ops_comment_dispatch.yml
This PR adds ChatOps commands for PRs. This makes it easy for new users to trigger some actions.
Supported commands:
- `/help`: Creates a comment in the PR which mentions one of the maintainers so he can help the user out
Needs #656
=> ci: add ChatOps command `/help`

main.tf, variables.tf
Adds supports for setting timezone for the AWS autoscaling configuration.
NO - Terraform will detect a change to the timezone attribute, but `Etc/UTC` should be the default anyway.
Changing the timezone:
```hcl
enable_schedule = true
schedule_config = {
scale_out_recurrence = "0 5 * * MON-FRI"
scale_out_count      = 1
scale_out_time_zone  = "Europe/Amsterdam"
scale_in_recurrence = "0 19 * * *"
scale_in_count      = 0
scale_in_time_zone  = "Europe/Amsterdam"
}
```
plan:
And result:
Defaults:
```hcl
enable_schedule = true
schedule_config = {
scale_out_recurrence = "0 5 * * MON-FRI"
scale_out_count      = 1
scale_in_recurrence = "0 19 * * *"
scale_in_count      = 0
}
```
Plan:
And result:
=> feat: add support for timezone in AWS autoscaling config

.github/workflows/lint_pr_title.yml, .github/workflows/pr-opened.yml, .github/workflows/release.yml, .github/workflows/slash_ops_commands.yml, .github/workflows/slash_ops_comment_dispatch.yml, .github/workflows/stale.yml, .github/workflows/update_docs.yml
A good practice in supply chain security is to have immutable builds. Currently GH tags for actions are mutable, even when a specific tag like x.y.z is used. Therefore, this PR locks the actions on the SHA. Dependabot can update the actions based on SHA, including the comments poitning to the underlying version.
NO
n/a
=> chore: lock gh actions on sha instead of tag

main.tf
Pull request #510 missed one last usage of `var.enable_manage_gitlab_token` as noted by @npalm in a resolved review comment.
No, this requires the same level of migration as #510.
Verified in my production runner setup which is similar to the default example with some minor tweaks.
v6.1.0 fails with this error:
```
Error: Null condition
on main.tf line 511, in resource "aws_iam_role_policy_attachment" "ssm":
511:   count = var.enable_manage_gitlab_token ? 1 : 0
├────────────────
│ var.enable_manage_gitlab_token is null
The condition value is null. Conditions must either be true or false.
```
This change fixes this resulting in a valid plan.
=> fix: null condition for enable_manage_gitlab_token in release v6.1.0

README.md
We renamed the workflows but didn't update the status badge in the `README.md`. Thus a broken image is shown only. This PR corrects the link to the workflow badge.
No.
None.
=> chore: fix broken CI badge in `README.md`

.github/workflows/lint_pr_title.yml
This PR allows the PR linter to succeed if there is only one commit as we switched to a default commit message of "PR title and PR body". So nothing is calculated by GitHub at time of merging. There will never be a problem with overwriting the commit message accidentally as it is fixed now.
It avoids this error message from the linter: `Error: Pull request has only one commit and it's not semantic; this may lead to a non-semantic commit in the base branch (see https://github.community/t/how-to-change-the-default-squash-merge-commit-message/1155). Amend the commit message to match the pull request title, or add another commit.`
In addition we run the check on the pull request instead of the pull request target. This way we get an elevated `GITHUB_TOKEN` and can access the PR.
No
None
=> ci: fix PR linter (single commit and permissions)

.github/workflows/ci.yml
Adds the `GITHUB_TOKEN` to the TfLint action to avoid hitting the Github API rate limiting as explained here: https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
I saw many pipelines failing with the rate limiting error.
No.
Check that the TfLint job still runs in this PR.
=> ci: avoid API rate limiting setting up TfLint

.github/workflows/ci.yml, CHANGELOG.md
`CHANGELOG.md` is an auto-generated file. It makes no sense to check whether the links are correct or not as we shouldn't change this file.
No
=> ci: do not check the links in `CHANGELOG.md`

.github/workflows/ci.yml, modules/cache/main.tf
Currently we are using `v6`. But this introduces new checks on the fly which is cumbersome. This PR fixes the version used.
No
=> ci: fix Megalinter version

modules/cache/main.tf
This resolves an issue related to the April 2023 S3 API changes. More info can be found here: https://github.com/hashicorp/terraform-provider-aws/issues/28353
Closes #814
Remove the explicit private ACL that leads to an error during the apply phase as with the new security defaults, it should no longer be needed. I'm not 100% on the implications of removing this resource for existing deployments, so if that's a concern we can go the route of adding the explicit `aws_s3_bucket_ownership_controls` resource as per the related issue.
NO
- Solves the issue in #814 using the recommendations from: https://github.com/hashicorp/terraform-provider-aws/issues/28353
- manually tested and checked that the cache is still accessible
=> fix: remove explicit aws_s3_bucket_acl

outputs.tf
Some credentials are leaking through the output `runners_user_data`. We don't want to see these in our pipeline logs.
No
No verification done.
=> chore: make the `runners_user_data` a sensitive output

README.md
Changes the `README.md` and 
- adds an early announcement of the upcoming major release 7.
- removes outdated announcements
=> docs: announce the major release v7

README.md, locals.tf, main.tf, template/gitlab-runner.tftpl, variables.tf
Adds the ability to read the Gitlab registration token from SSM. If no registration token is passed in, it will look in SSM to find the token to use. This prevents the token from being leaked as part of the user_data.
```hcl
module "gitlab_runner" {
gitlab_runner_registration_config = {
registration_token = "" # this is the default value too
}
secure_parameter_store_gitlab_runner_registration_token_name = "name-of-ssm-parameter-holding-the-registration-token"
```
Closes #776
Precondition for #186 to get rid of pre-registered runners.
NO
I modified the runner-default example to not pass in a registration token and added the token to SSM instead. Then I started up the runner and confirmed that it successfully registered with Gitlab.
=> feat: add option to read Gitlab Runner Registration token from SSM

.github/workflows/lint_pr_title.yml
This PR fixes the authorization issues with the PR title linter GitHub workflow action.
In case the PR comes from a fork, the action wasn't able to lint the PR title as the `GITHUB_TOKEN` wasn't allowed to access the PR (created in our project). Error message shown: `Error: Resource not accessible by integration`.
As we verify the PR title only, we can simply run in `pull_request_target` instead of `pull_request`.
Verified with [Hapag-Lloyd/test](https://github.com/Hapag-Lloyd/test) and [kayman-mk/test](https://github.com/kayman-mk/test)
=> ci: fix PR title linter authorization problems

README.md, main.tf, template/runner-config.tftpl, variables.tf
This PR adds the `wait_for_services_timeout` docker setting for the executor (see https://docs.gitlab.com/runner/configuration/advanced-configuration.html#the-runnersdocker-section).
I've found #513 while looking for a solution to our problem. After migrating from the Kubernetes executer to the docker-machine executer, we have had a couple of Gitlab jobs that are always waiting 30s before actually running the defined steps.
I am aware of #819 but I believe this might be a quick win.
NO
In order to test my change, I recommend to set
```hcl
debug = { "output_runner_config_to_file": true, "output_runner_user_data_to_file": false }
```
and then run `terraform plan`.
It will print the locally rendered `config.toml` that now contains the new setting:
```
[...]
pre_clone_script = "" …
```
=> feat: add support for `wait_for_services_timeout` option

locals.tf, variables.tf
While checking the PR, I was not able to switch from main to the refactory-varialbes branch for the example-default.
- fix a missing default
- add a null check in stated of a string check
=> fix: add missing defaults

template/runner-config.tftpl
In rare cases the `amazonec2-tags` may contain empty elements which show up as `,__PARENT_TAG__` which is not a valid value for AWS API to create an instance.
The problem is that `runner_tags` must be removed if it is empty. Otherwise the empty element is inserted into the final string which results in a preceding `,`.
Closes #933 
Verified manually with
- no tags --> `__PARENT_TAG__`
- with tags --> `tag1,value1,__PARENT_TAG`
=> fix: remove empty elements from tag list

examples/runner-default/versions.tf, main.tf, template/runner-config.tftpl, variables.tf
This feature allows to support `MaxGrowthRate` which limits the number of instances added in parallel by the Runner. The default of `0` (unlimited) is used if no value is given.
The parameter is added to `runner_worker_docker_machine_instance` as this is the only Runner type for which it makes sense. All other types are not able to scale and thus it is not a `runner_worker` parameter.
See [advanced-configuration](https://docs.gitlab.com/runner/configuration/advanced-configuration.html#the-runnersmachine-section)
Closes #851 
NO
- do not set the parameter --> `MaxGrowthRate` in config file is 0.
- set the parameter to any value --> `MaxGrowthRate` in config file is "any value"
=> feat: add `MaxGrowthRate` to limit the number of instances added in parallel

migrations/migrate-to-7-0-0.sh
The instance types for the fleet are not converted. In this case the module uses a default value `m5.large`. So all created instances are `m5.large` instances which is usually not wanted.
If the migration script was used to convert the module call to version 7, it is very likely that you find the following in your module call:
```hcl
runner_instance = {
docker_machine_types_fleet = ["t3.medium"] # your instance types here
}
```
The variable `docker_machine_types_fleet` does not exist, but Terraform does not report an error.
This PR fixes the migration script and produces the following correct code:
```hcl
runner_worker_docker_machine_instance = {
types                    = ["t3.medium"]
}
```
No
Verified locally that the script produces the output as described above.
=> fix: convert the fleet instance type in migration script

README.md, renovate.json
Group all dependency updates into one PR
Open the PR once a week (Monday morning)
Renovate activated badge
NO
=> chore: reconfigure renovate to group all updates into one PR once a week

renovate.json
Terraform updates were scheduled for Sunday, everything else for once a week which could be another weekday. Now all dependency updates are done once a week.
=> chore: do all dependency updates once a week on the same day

renovate.json
We should update the dependencies in all directories. Do not leave anything out.
=> chore: do not ignore any path when Renovate

CONTRIBUTING.md, README.md, docs/pitfalls.md, docs/usage.md
This PR restructures the whole documentation and adapts it to the changed variable names introduces with v7 release.
- shorten the main document
- underline that contributions are welcome
- create a pitfall document
- moving the detailed concepts into a separate file
=> docs: restructure and streamline documentation

policies/instance-kms-policy.json
Since the [addition of KeyId](https://github.com/cattle-ops/terraform-aws-gitlab-runner/commit/f25a86b5ada3e78a56c33db07a0110354f5e2e5d#diff-dc46acf24afd63ef8c556b77c126ccc6e578bc87e3aa09a931f33d9bf2532fbbR18) to the SSM parameter used to store the registration token, the replacement of the parameter following a failed token verification fails.  This is due to a missing Encrypt permission on the customer managed KMS key.
The initial put-parameter presumably passes due to a shortcut on the encryption when the value is null, but the [subsequent overwrite attempt](https://github.com/cattle-ops/terraform-aws-gitlab-runner/blob/5100efd3445c3f06e5089d970da5a3a0341624eb/template/gitlab-runner.tftpl#L53) fails.
NO
Manual addition of the kms:Encrypt permission has been proved to resolve the runner …
=> fix: add kms:Encrypt permission, as needed since f25a86b5

template/gitlab-runner.tftpl
We have a script which removes the GitLab Runner from GitLab in case it is shutdown. This script wasn't run automatically. This PR adds a Systemd service which starts the removal script at shutdown automatically.
Closes #1014 
No
Verified manually that the Runner is removed from GitLab at shutdown.
=> fix: run the GitLab Runner deregistration process at shutdown

.github/workflows/stale.yml
Some of the issues/PRs are long-lived. But they are set to stale after some weeks. As it creates some manual workload to remove the stale label, this PR introduces a `work-in-progress` label. Issues/PRs with this label are never set to stale.
No
None
=> ci: exempt issues and PRs from becoming stale automatically

outputs.tf
Due to calls to `nonsensitive` in case the data is sensitive or not calling the function in the other case, the code gets very complex. The output variable `runner_config_toml_rendereded` was introduced for easier debugging, but we still have the option to write the whole Runner configuration to a local file (`debug.write_runner_config_to_file`).
This "fixers" that issue by just deleting the output variable.
Closes #1018
Usually not. For debugging purposes, set the `debug.write_runner_config_to_file` to `true`. The configuration is written to a file on your local disk (directory `debug/`)
Only linted as this is only deleting an output variable.
=> fix: delete the 'runner_config_toml_rendereded' output variable

.cspell.json, renovate.json
Configures Renovate to auto-merge all PRs which are releated to non-major updates.
=> ci: activate the auto-merge of non-major updates

.github/workflows/auto-approval.yml
Use a GitHub PAT to approve the Renovate pull requests. This saves some time as we can merge these pull requests automatically. Tokens generated by an app do not work here as apps can't be added to the `CODEOWNERS` file. So their approvals never count.
=> ci: use a PAT to approve the Renovate pull requests

policies/instance-secure-parameter-role-policy.json
This pull request addresses a bug where utilizing the module with 'access_token_secure_parameter_store_name' instead of 'registration_token' results in a failure to retrieve the parameter value, leading to an error. The issue manifests when the module is applied, and subsequent attempts by the EC2 instance to fetch the parameter during runtime result in a 'permission denied' error, as observed in CloudWatch logs
Closes #1057 
No
=> fix: add missing GetParameter policy

variables.tf
Just a small thing I spotted while going through the docs. The variable `agent_schedule_enable` does not exist. The PR changes the name to `runner_schedule_enable` for a better documentation.
=> docs: wrong reference to variable

template/gitlab-runner.tftpl
The startup shell script of the Agent instance was broken due to missing tests (to be addressed in #1088 ). Fixed the script and validated it with shellchecker.
- `if` needs `then`
- no spaces in `=` assignments
- use `$` to get the value of a variable
- module deployed in the test environment. Runners were spawn, jobs processed.
- Cloudwatch logs checked for errors, none found
=> fix: repair errors in startup shell script

docs/usage.md, examples/runner-certificates/main.tf, examples/runner-certificates/variables.tf, examples/runner-default/main.tf, examples/runner-default/variables.tf, examples/runner-docker/main.tf, examples/runner-docker/variables.tf, examples/runner-pre-registered/main.tf, examples/runner-pre-registered/variables.tf, examples/runner-public/main.tf, examples/runner-public/variables.tf, main.tf, template/gitlab-runner.tftpl, variables.tf
GitLab announced then [Next GitLab Runner Token Architecture](https://docs.gitlab.com/ee/architecture/blueprints/runner_tokens/index.html#proposal). Runners have to be registered manually.
This PR adds a new import parameter `runner_gitlab.preregistered_runner_token_ssm_parameter_name` holding the name of a SSM parameter (type: `SecuredString`). This parameter contains the GitLab Runner token obtained from GitLab. All other registration methods will still work, but have been marked as deprecated and will be removed with [v8.0.0](https://github.com/cattle-ops/terraform-aws-gitlab-runner/milestone/4) end of the year.
This also solves the problems with Runners removed from GitLab at shutdown, resulting in new Runners not able to start.
Closes #1074 and #1109
=> feat: add option to use a pre-registered Runner

template/logging.tftpl, variables.tf
Adds support for Amazon Linux 2023 and removes the `dmesg` logs from Cloudwatch as it wasn't useful at all.
Closes #1137
=> feat: use Amazon Linux 2023 for runner manager instance

modules/terminate-agent-hook/main.tf
Increases the timeout to 90s to give the Lambda function more time to complete. #1149 describes errors in case of big installations (number of EC2 instances).
None.
=> fix: increase timeout for EC2 termination lambda

template/runner-config.tftpl
Adds the `pre_get_sources_script` (GitLab Runner 17+) parameter which is filled with the value of `pre_clone_script` (GitLab Runner < 17).
The parameter was renamed. Deprecation warnings are shown in the logs of GitLab Runner 16. GitLab Runner 17 simply ignores the parameter and therefor the whole script. This might result in failing pipelines.
=> feat: add `pre_get_sources_script` for GitLab Runner 17+

template/gitlab-runner.tftpl
Add an error message to the GitLab Runner log in case the pre-registered token can't be found in the SSM parameter store.
Closes #1139
=> chore: show error message if the pre-registered token cannot be found

locals.tf, main.tf, modules/terminate-agent-hook/main.tf, modules/terminate-agent-hook/variables.tf, variables.tf
Add `var.runner_terminate_ec2_timeout_duration` with a default of 90 seconds. Makes it possible to configure the timeout in case hundreds of workers are controlled by a single GitLab Runner Agent. Otherwise the Lambda function might fail and does not remove any worker in case the Agent is stopped.
Closes #1149
=> feat: make the graceful terminate Lambda timeout configurable

main.tf
PascalCase was used to create the `[[runners.autoscaler.policy]]` which is wrong according to the documentation. This PR fixes the names in the configuration file. `IdleCount` --> `idle_count` 
The worker instances were used once and then terminated. This resulted in a high load of some AWS autoscaling APIs and we got rate limiting. In the end most pipelines failed.
Deployed the changes into my environment. The worker machines are reused now.
=> fix: use correct names for autoscaler policies configuration

template/runner-docker-autoscaler-config.tftpl
The new options `update_interval` and `update_interval_when_expecting` are strings and need a `"` around the value. Otherwise the configuration file has the wrong format and the Agent might not work as expected.
Closes #1176
=> fix: add `"` to the new `update_interval_*` options of the autoscaler

docker_autoscaler.tf, main.tf, variables.tf
Add the possibility to have multiple subnets for runner manager instance with docker-autoscaler runner type.
Add the variable `enabled_metrics` for docker autoscaler autoscaling group
No
Tested on our side on a production runner.
To enable metrics for docker autoscaler autoscaling group you have to pass a list of metrics, here is my conf
```
runner_worker_docker_autoscaler_asg = {
...
enabled_metrics  = ["GroupMinSize",  "GroupMaxSize", "GroupInServiceInstances", "GroupPendingInstances", 
"GroupStandbyInstances", "GroupTerminatingInstances", "GroupTotalInstances"]
```
=> fix: autoscaler asg subnets and add possibility to enable metrics for asg

variables.tf
Update variable description for `runner_install` to match the expected variable for `amazon_ecr_credential_helper`
No
=> docs: fix amazon_ecr_credential_helper typo in runner_install variable description

modules/terminate-agent-hook/main.tf
Hello, this is a follow up of the problems reported in #1171
After digging deeper into the problem, we figured out some more details.
We use Atlantis, running in a Kubernetes cluster, to plan & apply Terraform changes.
The Atlantis PVC is backed by a NFS based backend, therefore not really POSIX compliant. Our guess is that this causes the `source_code_hash` to flap between two different values `STtJd0//CpU4WGQcc2ojckEcEHtCrD8W2fpx9E1TL64` (Which is the result if the file permissions are 0622) and `47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=` (Where I couldn't figure out which exact permissions cause this value to be computed. I tried almost all variantes such as 0644, 0777, etc.)
When running a plan via Atlantis the result sometimes changes within minutes. While doing the research, we …
=> chore: set specific file mode for the zipped lambda function to ensure consistent checksums

docker_autoscaler.tf, main.tf
Some of the `tag_specifications` were missing and are added in this PR. Leads to more resources being tagged correctly.
Closes #1207
=> fix: add missing `tag_specifications` for launch templates

data.tf, docker_autoscaler.tf, main.tf, variables.tf
At the moment the latest AMI is read at deploy time. But to get an immutable infrastructure we have to fix the AMI. This PR adds variables to set the AMI id.
=> feat: add variables to specify the AMI ids

.github/workflows/ci.yml, .github/workflows/feature_branch-megalinter.yml
According to a warning in the logs, we can safely replace the `GITHUB_TOKEN` by workflow permissions.
=> ci: replace `GITHUB_TOKEN` by workflow permissions in Megalinter

docker_machine_security_group.tf
The `runner_worker_ingress_rules` and `runner_worker_egress_rules` have to be attached to the correct security group. At the moment the module always attaches the rules to the docker machine security group which does not exist when `docker-autoscaler` is used.
=> fix: do not create security group rules for `docker+machine` if `docker-autoscaler` selected

template/runner-docker-machine-config.tftpl
The EBS volume encryption was activated only, if the fleeting plugin is activated. It seems that we can always activate the encryption as the docker-machine parameters are not tied to the fleeting plugin.
Fixes #1242
=> fix: always encrypt EBS volumes if the KMS key is given

outputs.tf
For the `docker-autoscaler` workers the security group id was not returned, which is added by this PR. According to the description of the variable, we can expect it for every worker type creating separate instances.
Fixes #1241
=> fix: return security group id for docker-autoscaler in `runner_sg_id`

examples/runner-fleeting-plugin/main.tf
Otherwise it deploys unusable asg with max=0
=> docs: add `max_jobs` to docker-autoscaler example

modules/terminate-agent-hook/iam.tf
Just noticed that the termination Lambdas do no longer start. Error message is
```
Calling the invoke API action failed with this message: Lambda was unable to decrypt the environment variables
because KMS access was denied. Please check the function's KMS key settings. KMS Exception:
AccessDeniedExceptionKMS Message: User: <arn here> is not authorized to perform: kms:Decrypt on resource:
<arn here> because no identity-based policy allows the kms:Decrypt action (Service: Kms, Status Code: 400,
Request ID: <request id here>)
```
This PR adds the `kms:Decrypt` action to the Lambda role allowing the Lambda function to decode the environment variables.
=> fix: allow terminate Lambda to access kms key

modules/terminate-agent-hook/main.tf, modules/terminate-agent-hook/versions.tf, versions.tf
This pull request updates the `terminate-agent-hook` Lambda function to use Python 3.13 and the Arm64 architecture (Graviton2). Lambda functions powered by Graviton2 are designed to deliver up to 19% better performance at 20% lower cost, improving both efficiency and cost-effectiveness.
The change also updates the required AWS provider version to `>= 5.76` to ensure compatibility with the latest AWS resources and services.
=> chore: update the terminate-agent-hook lambda to Python 3.13 with Arm/Graviton2

variables.tf
Allow HTTP (port 80) traffic by default to allow commonly-used resources to be accessible from the `docker-autoscaler` runner workers.
Fix #1302.
No
See #1302 for test cases.
=> fix: allow HTTP egress traffic to all destinations

docker_autoscaler_policy.tf, docker_machine.tf, kms.tf, main.tf, runner_policy.tf, versions.tf
Upgrades the module to `hashicorp/aws >= 6.0.0`. The version is out for 3+ months and we can fix a deprecation warning for the `aws_region` datasource.
`The attribute "name" is deprecated. Refer to the provider documentation for details.`
Fixes #1295
=> chore(deps): update to Terraform AWS provider 6.0.0+
